### ISSUE TITLE
An error occurred during translation.

### ISSUE THREAD

**Issue by ZeRoZeRoRaZ** [patcher454/DeepLTranslatorPowerToys#3]
I am getting the following error while I try to use the plugin on v0.86.0 of PowerToys.
![image](https://github.com/user-attachments/assets/e7192b7c-75d5-4d55-afcc-dd19cfffd034)

**Comment by patcher454** [comment]
Hi @ZeRoZeRoRaZ 
Thank you for your report.
This issue is likely caused by an incorrectly entered DeepL API key. 
Please verify that the API key is valid and, if so, ensure that it is entered in the following format: DeepL-Auth-Key {API KEY}.

It should look like the image below

![image](https://github.com/user-attachments/assets/1122bbc3-e170-4757-97d9-355d473984d6)

And if you've updated the plugin to [v1.0.2(0.86.0)](https://github.com/patcher454/DeepLTranslatorPowerToys/releases/tag/v1.0.2(0.86.0)) and still see `An error occurred during translation`, Please let me know.

**Comment by ZeRoZeRoRaZ** [comment]
It works.
Thanks!
